### ISSUE TITLE
Support multi-line equations

### ISSUE THREAD

**Issue by JasonGross** [Divide-By-0/autolatex#23]
Please add a mode to support multi-line equations, e.g.,
```
\[\begin{align*}
\underline{n} & := \{0, 1, \ldots, n-1\} \\
X & := \underline{64}^4 \\
D & := U(0, 63) = \test{the uniform distribution} \\
PDF_D(x) & := \begin{cases} \frac{1}{64} & \text{if } 0 \le x < 64 \\ 0 & \text{otherwise} \end{cases}
\end{align*}\]
```
It would perhaps be nice to have a "safer" version of this mode that only works with `\[` and `\]` (to ensure that text is not captured) and requires that there is no `\[` before the next `\]`.

**Comment by Divide-By-0** [comment]
Hey! We should support \\ after each line, or shift+enter for newlines [as opposed to enters]. Does that work for you? I notice your second last line does not have a shift enter nor \\.

**Comment by JasonGross** [comment]
Ah, I see!  Maybe the short list of instructions in the panel should include something about how multiline equations need to match one of these formats?

**Comment by grimsteel** [comment]
The panel already includes that
![image](https://github.com/user-attachments/assets/b6d3b7b2-23d8-4618-83a1-0d0f514cfb04)

**Comment by haohanyuzmx** [comment]
![Image](https://github.com/user-attachments/assets/b207a673-8fe6-40d2-bb9a-d69409883451)

![Image](https://github.com/user-attachments/assets/6cc10b97-6c3a-450f-aaed-6fb2774b5547)

I'm not very good at how to implement multi-line. In the picture, second only delete first line of first, but second picture in one line. I use shift+enter for new line and add "\\" to the end

```
$$
f(x) &= a\cdot b \\
f(y)=b \\
abc \\
bcd \\
ddd \\
$$
```
