### ISSUE TITLE
Fix tildas

### ISSUE THREAD

**Issue by Divide-By-0** [Divide-By-0/autolatex#27]
> When I use a ~ to put a space between two terms in an equation for readability, AutoLaTeX decides to simply refuse to render anything after the ~ mark. It prints the equation leading up to that term, but then everything after it is blank.

> Has anyone else reported this issue? I know it is indeed a bug because I compulsively use ~ in documents with AutoLaTeX and I've only run into this bug in the last few days or maybe the past couple of weeks.

**Comment by grimsteel** [comment]
Seems to be an issue with codecogs:

```
https://latex.codecogs.com/svg.image?\inline&space;&space;x~y
```

![](https://latex.codecogs.com/png.image?\inline&space;\dpi{110}\bg{white}&space;x~y)

It's not exactly the same, but I could replace tildes with `\,` for CodeCogs

```
https://latex.codecogs.com/svg.image?\inline&space;&space;x\,y
```

![](https://latex.codecogs.com/png.image?\inline&space;\dpi{110}\bg{white}&space;x\\,y)


---

ALso, is there any reason why we're not using something like MathJax to render the equations on Apps Script itself?

**Comment by Divide-By-0** [comment]
> Seems to be an issue with codecogs:
> 
> ```
> https://latex.codecogs.com/svg.image?\inline&space;&space;x~y
> ```
> 
> ![](https://camo.githubusercontent.com/ba8970eb2a974b309493a746de56e6a761de6e24a453ba7dfebb7b2e8fe5f4c1/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f706e672e696d6167653f253543696e6c696e652673706163653b253543647069253742313130253744253543626725374277686974652537442673706163653b787e79)
> 
> It's not exactly the same, but I could replace tildes with `\,` for CodeCogs
> 
> ```
> https://latex.codecogs.com/svg.image?\inline&space;&space;x\,y
> ```
> 
> ![](https://camo.githubusercontent.com/41db92da7cf0ace8dfd7a27b65ffdb7938e027c722d29363181bcb8f46a1532c/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f706e672e696d6167653f253543696e6c696e652673706163653b253543647069253742313130253744253543626725374277686974652537442673706163653b782535432c79)
> 
> ALso, is there any reason why we're not using something like MathJax to render the equations on Apps Script itself?

We really should be using mathjax. I'm down if you want to make that change.
