### ISSUE TITLE
Don't delete bad equations, color them red and ignore them

### ISSUE THREAD

**Issue by Divide-By-0** [Divide-By-0/autolatex#7]
Also have more robust error handling so that the rest of the equations in the doc properly render. Right now, rendering just stops entirely.

Feedback:

Hi, 

Thanks a LOT for your addon. I can draft my thesis in google docs and this really helps me against procrastination since Google Docs is so accessible.

Here is a minor issue: when an equation is incorrect, eg $$\left$$, I get an error message in the addon and the equation gets deleted. This is quite annoying if it took me a long time to write. Also I can be at another place in the document and not notice it being deleted. It would be much better to color it in red instead of deleting it.

Best,
Louis...

**Comment by grimsteel** [comment]
Doesn't this already happen?

Before rendering:
![image](https://github.com/Divide-By-0/autolatex/assets/115331356/499b3bba-2edb-4dfd-8304-1c4d65a0833a)

After rendering:
![image](https://github.com/Divide-By-0/autolatex/assets/115331356/f036a08c-ac40-4c69-a215-083ba79b0d05)

Derendering the bad equation works as expected
![image](https://github.com/Divide-By-0/autolatex/assets/115331356/403e84a0-6097-473b-b886-86baee5c2af6)
